sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  global:
    # Ignore warnings when running specs.
    - RUBYOPT="-W0"
  matrix:
    - CHEF_VERSION=12.9.38 INSTANCE=default-debian-7
    - CHEF_VERSION=12.9.38 INSTANCE=default-debian-8
    - CHEF_VERSION=12.9.38 INSTANCE=default-ubuntu-1204
    - CHEF_VERSION=12.9.38 INSTANCE=default-ubuntu-1404
    - CHEF_VERSION=12.9.38 INSTANCE=default-centos-6
    - CHEF_VERSION=12.9.38 INSTANCE=default-centos-7
    - CHEF_VERSION=current INSTANCE=default-debian-7
    - CHEF_VERSION=current INSTANCE=default-debian-8
    - CHEF_VERSION=current INSTANCE=default-ubuntu-1204
    - CHEF_VERSION=current INSTANCE=default-ubuntu-1404
    - CHEF_VERSION=current INSTANCE=default-centos-6
    - CHEF_VERSION=current INSTANCE=default-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec rake
      env: UNIT_AND_LINT=1
